config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users, param: :username do
    get 'best', on: :member
  end
  resources :questions, except: [:show, :new, :index] do
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :hashtags, only: [:show], param: :name
  resource :session, only: [:new, :create, :destroy]
end

app/models/question.rb
class Question < ApplicationRecord
  REGEXP = (/(?:\s|^)#(?!(?:[[:digit:]]+|[[:alnum:]]+_|_[[:alnum:]]+)(?:\s|$))([[:alnum:]]+(?:_[[:alnum:]]+)*)(?=\s|$)/).freeze

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :hashtags

  validates :user, presence: true
  validates :text, presence: true, length: { maximum: 255 }

  before_save :check_hashtags

  private

  def check_hashtags
    hashtags.clear unless hashtags.empty?

    hashtags_array = if answer.present?
                       (text.scan(REGEXP).flatten + answer.scan(REGEXP).flatten).map(&:downcase).uniq
                     else
                       text.scan(REGEXP).flatten.map(&:downcase).uniq
                     end

    create_hashtags_for_question(self, hashtags_array)
  end

  def create_hashtags_for_question(question, hashtags_array)
    hashtags_array.map do |item|
      hashtag = Hashtag.find_or_create_by(name: item.downcase)
      question.hashtags << hashtag
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to(user_path(@question.user), notice: I18n.t('controllers.questions.created'))
    else
      render :edit
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to(user_path(@question.user), notice: I18n.t('controllers.questions.updated'))
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    user = @question.user
    @question.destroy
    redirect_to(user_path(user), notice: I18n.t('controllers.questions.destroyed'))
  end

  private

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  def check_captcha(model)
    if current_user.present?
      true
    else
      verify_recaptcha(model: model)
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_button_and_counter_for_likes.html.erb
<% pre_like = question.likes.find { |like| like.user_id == current_user.id} if current_user.present? %>

<%= link_to t('.likes', count: question.likes.count), question_likes_path(question), method: :get %>

<% if pre_like %>
  <%= button_to question_like_path(question, pre_like), class: 'button button-small button-dark', method: :delete, remote: current_user.present? do %>
    <%= t('.dislike') %> <%= fa_icon('heart') %>
  <% end %>
<% else %>
  <%= button_to question_likes_path(question), class: 'button button-small button-dark', method: :post, remote: current_user.present? do %>
    <%= t('.like') %> <%= fa_icon('heart-o') %>
  <% end %>
<% end %>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question, html: { id: 'invisible-recaptcha-form' }) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, class: 'form-label' %>
      <% if @question.user == current_user && @question.text.present? %>
        <%= f.text_area :text, disabled: true, class: 'form-textarea' %>
      <% else %>
        <%= f.text_area :text, class: 'form-textarea' %>
      <% end %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <div class="form-action buffer-both">
      <% if current_user.present? %>
        <%= f.submit t('.save'), class: 'button button-dark button-small' %>
      <% else %>
        <%= invisible_recaptcha_tags callback: 'submitInvisibleRecaptchaForm', text: t('.save'), class: 'button button-dark button-small' %>
      <% end %>
      <%= t('.alt') %>
      <%= link_to t('.back'), user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_hashtag_question.html.erb
<div class="hashtag-question">
  <% if @questions.empty? %>
    <%= t('.empty') %>
  <% else %>
    <% @questions.each_with_index do |question, i| %>
      <%= t('.question_for') %>
      <%= link_to "@#{question.user.username}", user_path(question.user) %>
      <%= link_to t('.go_to_question'), "#{user_path(question.user)}#question_#{question.id}" %>
      <%= render partial: 'questions/question', locals: { question: question, question_counter: i } %>
    <% end %>
  <% end %>
</div>

app/views/questions/_question.html.erb
<% questions_block_id = "question_#{question.id}" %>
<% question_number = @questions.nil? ? question_counter : @questions.size - question_counter %>
<% question_link = request.base_url + "#{user_path(question.user)}#q#{question.id}" %>

<div id="<%= questions_block_id %>" class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= render_with_hashtags(question.text) %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= render_with_hashtags(question.answer) %>
      </div>
    <% end %>

    <div class="question-additional-information">
      <div class="question-likes">
        <%= render partial: 'questions/button_and_counter_for_likes', locals: { question: question } %>
      </div>
      <div class="question-date-author-content">
        <div class="question-author">
          <% if question.author.present? %>
            <%= link_to_unless_current "@#{question.author.username}", user_path(question.author) %>
          <% else %>
            <p><%= t('.anonymous') %></p>
          <% end %>
        </div>
        <div class="question-date">
          <%= l(question.created_at, format: :short) %>
        </div>
      </div>
      <div class="question-link">
        <%= t('.question_number', count: question_number) %>
        <div class="tooltip">
          <button class="copy-question-link-to-clipboard button button-small button-dark" id="number-<%= question_number %>" data-link="<%= question_link %>">
            <%= content_tag(:span, t('.link.copy'), class: 'tooltip-text', id: "number-#{question_number}") %>
            <%= t('.link.name') %> <%= fa_icon('external-link') %>
          </button>
        </div>
      </div>
    </div>
  </div>

  <% if question.user == current_user %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: { confirm: t('.confirm_destroy') } %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium"><%= t('activerecord.models.question') %></h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>