config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users, param: :username do
    get 'best', on: :member
  end
  resources :questions, except: [:show, :new, :index] do
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :hashtags, only: [:show], param: :name
  resource :session, only: [:new, :create, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user

  # https://yerb.net/blog/2014/03/13/three-easy-steps-to-using-counter-caches-in-rails/
  belongs_to :question, counter_cache: true

  validates :user, presence: true
  validates :question, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # https://medium.com/full-taxx/how-to-add-likes-to-posts-in-rails-e81430101bc2
  # https://codereview.stackexchange.com/questions/154930/rails-like-and-unlike-posts
  # https://stackoverflow.com/questions/11945487/how-do-you-model-likes-in-rails

  before_action :find_question
  before_action :set_like, only: [:destroy]

  # GET /likes
  def index
    @users = User.find(@question.likes.map(&:user_id))
  end

  # POST /likes
  def create
    user = User.find(@question.user.id)

    respond_to do |format|
      format.html do
        if current_user.nil?
          flash[:notice] = I18n.t('controllers.likes.register')
          redirect_back(fallback_location: user_path(user))
        elsif already_liked?
          flash[:notice] = I18n.t('controllers.likes.already_liked')
          redirect_back(fallback_location: user_path(user))
        end
      end

      format.js { @question.likes.create(user_id: current_user.id) }
    end
  end

  # DELETE /likes/1
  def destroy
    @like.destroy
    @user = User.find(@question.user.id)
    @question_likes_count = @question.likes.count

    if @question_likes_count.zero?
      @questions_count = @user.questions.joins(:likes).where.not(questions: { id: @question.id }).count
      @answers_count = @user.questions.joins(:likes).where.not(questions: { id: @question.id, answer: nil }).count
      @unanswered_count = @questions_count - @answers_count
    end
  end

  private

  def set_like
    @like = @question.likes.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, question_id:
        params[:question_id]).exists?
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/create.js.erb
Turbolinks.clearCache();
$("#question_<%= @question.id %> .question-content .question-additional-information .question-likes")
    .html("<%= j(render(partial: 'questions/button_and_counter_for_likes', locals: { question: @question })) %>")

app/views/likes/destroy.js.erb
Turbolinks.clearCache();
<% if request.referer == best_user_url(@user.username) && @question_likes_count.zero? %>
  $('.user-statistics').html("<%= j(render(partial: 'users/user_statistics', locals:
    {
      questions_count: @questions_count,
      answers_count: @answers_count,
      unanswered_count: @unanswered_count
     })) %>");
  $("#question_<%= @question.id %>").remove();
<% else %>
  $("#question_<%= @question.id %> .question-content .question-additional-information .question-likes")
    .html("<%= j(render(partial: 'questions/button_and_counter_for_likes', locals: { question: @question })) %>");
<% end %>

app/views/likes/index.html.erb
<div class="user-questions buffer-both">
  <div class="questions-list">
    <div class="liked-question">
      <%= t('.question_for') %>
      <%= link_to "@#{@question.user.username}", user_path(@question.user) %>
      <%= render partial: 'questions/question', locals: { question: @question, question_counter: 1 } %>
    </div>
  </div>
</div>

<div class="like-header buffer-both">
  <h2 class="title-medium"><%= t('.title') %></h2>
</div>

<div class="content-wrapper buffer-both">
  <% if @users.empty? %>
    <div class="like-empty-users-title">
      <%= t('.empty') %>
    </div>
  <% else %>
    <div class="text-center">
      <% @users.each do |user| %>
        <div class="users-list-item">
          <div class="user-image-div user-image-div-small">
            <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
          </div>
          <span class="user-label-name"><%= link_to user.username, user_path(user) %></span>
        </div>
      <% end %>
    </div>
  <% end %>
</div>