config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users, param: :username do
    get 'best', on: :member
  end
  resources :questions, except: [:show, :new, :index] do
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :hashtags, only: [:show], param: :name
  resource :session, only: [:new, :create, :destroy]
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20_000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions, dependent: :destroy
  has_many :asked_questions, class_name: 'Question', foreign_key: 'author_id', dependent: :nullify
  has_many :likes, dependent: :destroy

  validates :username, presence: true, uniqueness: true, length: { maximum: 40 }, format: { with: /\A[0-9a-z_]+\z/i }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@(?:[-a-z0-9]+\.)+[a-z]{2,}\z/i}
  validates :avatar_bg_color, :avatar_border_color, :profile_text_color, format: { with: /\A#[\h]{6}\z/ }, allow_nil: true

  # Второй способ валидации почты пользователя с помощью gem email_address
  # https://github.com/afair/email_address
  # validates_with EmailAddress::ActiveRecordValidator, field: :email

  attr_accessor :password

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_validation :check_username
  before_save :encrypt_password

  def to_param
    username
  end

  def check_username
    self.username = username.downcase if username.present?
  end

  def encrypt_password
    if password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(
          password, password_salt, ITERATIONS, DIGEST.length, DIGEST
        )
      )
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)

    return nil unless user.present?

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )

    return user if user.password_hash == hashed_password

    nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :new, :create]
  before_action :authorize_user, except: [:index, :new, :create, :show, :best]

  def index
    @users = User.all
    @hashtags = Hashtag.all
  end

  def new
    redirect_to(root_url, alert: I18n.t('controllers.users.already_logged_in')) if current_user.present?
    @user = User.new
  end

  def create
    redirect_to(root_url, alert: I18n.t('controllers.users.already_logged_in')) if current_user.present?
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to(root_url, notice: I18n.t('controllers.users.created'))
    else
      render('new')
    end
  end

  def update
    if @user.update(user_params)
      redirect_to(user_path(@user), notice: I18n.t('controllers.users.updated'))
    else
      render('edit')
    end
  end

  def edit
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to(root_url, notice: I18n.t('controllers.users.destroyed'))
  end

  def show
    @new_question = @user.questions.build
    @questions = @user.questions.order(created_at: :desc)
    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  def best
    @new_question = @user.questions.build
    @questions = @user.questions.joins(:likes).distinct.order('likes_count desc')
    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count

    render('users/show')
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find_by(username: params[:username])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :gender, :avatar_url, :theme_color)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_statistics.html.erb
<div class="column-1-3">
  <h1 class="title-small"><%= @questions_count %></h1>
  <p><%= t('.question', count: @questions_count) %></p>
</div>
<div class="column-1-3">
  <h1 class="title-small"><%= @answers_count %></h1>
  <p><%= t('.answer', count: @answers_count) %></p>
</div>
<div class="column-1-3">
  <h1 class="title-small"><%= @unanswered_count %></h1>
  <p><%= t('.unanswered', count: @unanswered_count) %></p>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium"><%= t('.title') %></h1>

  <div class="column-1-2">
    <div class="user-header text-center buffer-bottom" style="background-color: <%= user_bg_color(@user) %>; color: <%= user_text_color(@user) %>;">
      <h1 class="title-medium" id="user_name_sandbox">
        <%= @user.name %>
      </h1>

      <div class="user-image-div" style="border-color: <%= user_border_color(@user) %>;">
        <%= image_tag(user_avatar(@user), class: 'user-image', id: 'user_avatar_url_sandbox', alt: "@#{@user.username}") %>
      </div>

      <h2 class="title-small buffer-top" id="user_nickname_sandbox">
        @<%= @user.username %>
      </h2>

      <p class="text-small" id="user_gender_sandbox">
        <%= @user.gender %>
      </p>
    </div>

    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :gender, class: 'form-label' %>
        <%= f.select :gender, t('.form.gender'), { include_blank: true }, class: 'form-select-field' %>
      </div>

      <div class="form-field">
        <%= f.label :avatar_url, class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <%= f.label t('.form.color_preferences'), class: 'form-label' %>
      <div class="form-field">
        <%= f.label :avatar_bg_color, class: 'form-label-color' %>
        <%= f.color_field :avatar_bg_color, value: "#{user_bg_color(@user)}", class: 'form-color-field' %>
      </div>

      <div class="form-field">
        <%= f.label :avatar_border_color, class: 'form-label-color' %>
        <%= f.color_field :avatar_border_color, value: "#{user_border_color(@user)}", class: 'form-color-field' %>
      </div>

      <div class="form-field">
        <%= f.label :profile_text_color, class: 'form-label-color' %>
        <%= f.color_field :profile_text_color, value: "#{user_text_color(@user)}", class: 'form-color-field' %>
      </div>

      <div class="form-field">
        <button id="user_reset_colors" class="button button-small button-dark">
          <%= t('.form.reset_colors') %>
        </button>
      </div>

      <div class="buffer-top-large buffer-bottom">
        <%= t('.form.password_change') %>
      </div>

      <div class="form-field">
        <%= f.label :password, t('.form.new_password'), class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, t('.form.new_password_confirmation'), class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action-buttons buffer-top">
        <%= f.submit t('.form.save'), class: 'button button-dark button-small' %>
        <%= link_to t('.form.destroy'), user_path(current_user), method: :delete,
                    data: { confirm: t('.form.confirm_destroy') },
                    class: 'button button-light button-small' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium"><%= t('.users_title') %></h1>
  </div>
  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
      <span class="user-label-name"><%= link_to user.username, user_path(user) %></span>
    </div>
  <% end %>
</div>

<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium"><%= t('.hashtags_title') %></h1>
  </div>
  <% @hashtags.each do |hashtag| %>
    <div class="hashtags-list-item">
      <%= link_to "##{hashtag.name}", hashtag_path(hashtag), class: 'hashtag-link' %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium"><%= t('.title') %></h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :gender, class: 'form-label' %>
        <%= f.select :gender, t('.form.gender'), { include_blank: true }, class: 'form-select-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit t('.form.register'), class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background-color: <%= user_bg_color(@user) %>; color: <%= user_text_color(@user) %>;">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <% if current_user == @user %>
    <div class="buffer-both">
      <%= link_to t('.edit'), edit_user_path(@user), style: "color: #{user_text_color(@user)}" %>
    </div>
  <% end %>

  <div class="user-image-div" style="border-color: <%= user_border_color(@user) %>;">
    <%= image_tag(user_avatar(@user), class: 'user-image', alt: "@#{@user.username}") %>
  </div>

  <h2 class="title-small buffer-top">
    @<%= @user.username %>
  </h2>

  <p class="text-small">
    <%= @user.gender %>
  </p>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= button_tag t('.ask_me'), type: 'button', class: 'button button-light', id: 'ask-button' %>
  </div>

  <div class="user-statistics container text-center">
    <%= render partial: 'user_statistics', locals:
      {
        questions_count: @questions_count,
        answers_count: @answers_count,
        unanswered_count: @unanswered_count
      } %>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-top">
    <div class="form">
      <%= form_for @new_question, html: { id: 'invisible-recaptcha-form' } do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "#{t('.form.for')} @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <div class="form-action">
          <% if current_user.present? %>
            <%= submit_tag t('.form.ask'), class: 'button button-small button-dark' %>
          <% else %>
            <%= invisible_recaptcha_tags callback: 'submitInvisibleRecaptchaForm', text: t('.form.ask'), class: 'button button-dark button-small' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="column-3-4">
  <div class="user-filter-bar buffer-top">
    <% if request.params[:action] == 'show' %>
      <%= link_to t('.latest'), user_path(@user), class: 'active' %>
      <%= link_to t('.top'), best_user_path(@user) %>
    <% else %>
      <%= link_to t('.latest'), user_path(@user) %>
      <%= link_to t('.top'), best_user_path(@user), class: 'active' %>
    <% end %>
  </div>

  <div class="user-questions buffer-both">
    <div class="questions-list">
      <%= render partial: 'questions/question', collection: @questions %>
    </div>
  </div>
</div>