config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users, param: :username do
    get 'best', on: :member
  end
  resources :questions, except: [:show, :new, :index] do
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :hashtags, only: [:show], param: :name
  resource :session, only: [:new, :create, :destroy]
end

app/views/layouts/_js_locales_info.html.erb
<%= javascript_tag do %>
  I18n.defaultLocale = "<%= I18n.default_locale %>";
  I18n.locale = "<%= I18n.locale %>";
  I18n.fallbacks = true;
<% end %>

app/views/layouts/_user_menu.html.erb
<div class="header-nav">
  <% if current_user %>
    <%= link_to "@#{current_user.username}", user_path(current_user) %> |
    <%= link_to t('.log_out'), session_path, data: { method: :delete } %>
  <% else %>
    <%= link_to t('.sign_up'), new_user_path, class: 'button button-light button-small' %>
    <%= link_to t('.log_in'), new_session_path, class: 'button button-light button-small' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><%= t('app.name') %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= render 'layouts/js_locales_info' %>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js"></script>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <div class="header-logo">
          <h1 class="header-title"><%= link_to t('app.name'), root_path %></h1>
        </div>

        <%= render partial: 'layouts/user_menu' %>
      </div>
    </div>

    <div class="content">
      <div class="container">
        <% if flash.any? %>
          <div class="content-wrapper buffer-both">
            <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
            <% end %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>